name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install project dependencies
        shell: bash
        run: |
          set -e
          cd "$GITHUB_WORKSPACE"

          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Restart bot service
        shell: bash
        run: |
          set -e

          sudo -n systemctl restart discord-music-bot
          systemctl status discord-music-bot --no-pager --lines=20
